@host=http://localhost:8080/api

post {{host}}/users/register
Content-Type: application/json

{
    "username": "c",
    "email":"c@gmail.com",
    "password": "crane3004"
}

####
post {{host}}/users/login
Content-Type: application/json

{
    "email":"b@gmail.com",
    "password": "crane3004"
}
###
get {{host}}/api/users/all

###
post {{host}}/hospitals/register
Content-Type: application/json

{
    "name": "mayowa",
    "email":"hospital@gmail.com",
    "password": "crane3004",
    "type": "public",
    "address": "here"
}
###
post {{host}}/hospitals/login
Content-Type: application/json

{
    "email":"hospital@gmail.com",
    "password": "crane3004"
}

###
get {{host}}/hospitals/get-user-profile/b

###
get {{host}}/users/profile

###
put {{host}}/hospitals/update-user-profile/<username>
Content-Type: application/json

{"bloodGroup": "A+"}
