@host=http://localhost:8080/api
# @host=https://upgraded-octo-train.onrender.com/api

post {{host}}/users/register
Content-Type: application/json

{
"username": "yusuf",
"email": "yusuf@gmail.com",
"password": "yusuf",
"fullname": "yusuf"
}

####
post {{host}}/users/login
Content-Type: application/json

{
    "email": "yusuf@gmail.com",
    "password": "yusuf"
}
###
get {{host}}/users/all

###
post {{host}}/hospitals/register
Content-Type: application/json

{
    "name": "mayowa",
    "email":"hospital@gmail.com",
    "password": "crane3004",
    "type": "public",
    "address": "here"
}
###
post {{host}}/hospitals/login
Content-Type: application/json

{
    "email":"hospital@gmail.com",
    "password": "crane3004"
}

###
get {{host}}/hospitals/get-user-profile/test

###
get {{host}}/users/profile

###
put {{host}}/hospitals/update-user-profile/test
Content-Type: application/json

{"gender": "Male"}
###
get {{host}}/users/all

###
post {{host}}/hospitals/create-doctor
Content-Type: application/json

{"fullName": "femi", "username": "femo", "email": "femifemo@gmail.com"}

###
get {{host}}/hospitals/get-doctors

###
post {{host}}/doctors/login
Content-Type: application/json

{"email": "femifemo@gmail.com", "password": "123456"}